services:
  db:
    image: postgres:16
    container_name: ezkitchen_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dev_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: ezkitchen_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "4000:4000"
    depends_on:
      - db
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    command: [ "-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up" ]
    depends_on:
      - db
volumes:
  dev_data:
